version: '3'
services:
  frontend:
    image: nicointe/agenda_front_imagen
    ports:
      - 4200:80
    depends_on:
      - backend
  backend:
    image: nicointe/agenda_back_imagen
    ports:
      - 7076:80

